//! L1-001 — Presence challenge/attestation wire payloads.
//!
//! A challenges B to prove it is alive NOW; B answers with a signed
//! attestation. Both envelopes are SIGNED and NEVER encrypted (attestations
//! must be verifiable by third parties in L1-003). Everything here is
//! ephemeral: 30s lifetime, never persisted, never backed up (LOCKED #2).
//!
//! Hardened per docs/plans/L1-001-attestation-presence.md (V2):
//! - the challenge is signed (anti-reflection, CPU symmetry)
//! - all self-reported fields in `RelayProof` are ADVISORY ONLY — the
//!   anti-Sybil gate reads exclusively the challenger's LOCAL RoleManager
//!   score for the attester (an attacker-controlled field is not a gate)

use serde::{Deserialize, Serialize};

use crate::error::TomProtocolError;
use crate::types::NodeId;

/// Nonce length in bytes (cryptographically random, generated by A).
pub const NONCE_LEN: usize = 24;

/// Max accepted `challenge_id` length (UUID v4 is 36 chars).
pub const MAX_CHALLENGE_ID_LEN: usize = 64;

/// Loose acceptance window on the RESPONDER side (B), in ms.
///
/// The network has no synchronized clocks (no NTP — that is the very premise
/// of M1.2), so B only applies a wide sanity bound against replayed ancient
/// challenges. The CHALLENGER (A) judges freshness strictly against its own
/// local clock (`issued_at`), never against B's claimed timestamp.
pub const RESPONDER_ACCEPT_WINDOW_MS: u64 = 120_000;

/// Payload of a `MessageType::PresenceChallenge` envelope (A → B).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PresenceChallengePayload {
    /// Unique challenge identifier (UUID v4, generated by A).
    pub challenge_id: String,
    /// 24-byte cryptographically random nonce; B echoes it back so the
    /// attestation is bound to THIS challenge.
    #[serde(with = "serde_bytes")]
    pub nonce: Vec<u8>,
    /// A's clock at emission (Unix ms). Advisory for B (loose window only).
    pub timestamp: u64,
    /// Identity of the challenger — must equal the envelope `from`.
    pub challenger_id: NodeId,
}

impl PresenceChallengePayload {
    pub fn to_bytes(&self) -> Vec<u8> {
        rmp_serde::to_vec(self).expect("PresenceChallengePayload serialization cannot fail")
    }

    pub fn from_bytes(data: &[u8]) -> Result<Self, TomProtocolError> {
        rmp_serde::from_slice(data).map_err(Into::into)
    }

    /// Structural validation on the responder side (B).
    ///
    /// `now` is B's local clock; only a LOOSE window is applied (see
    /// [`RESPONDER_ACCEPT_WINDOW_MS`]) — strict freshness is the challenger's
    /// job, against its own clock.
    pub fn validate(&self, now: u64) -> Result<(), TomProtocolError> {
        if self.nonce.len() != NONCE_LEN {
            return Err(TomProtocolError::InvalidEnvelope {
                reason: format!(
                    "presence nonce must be {NONCE_LEN} bytes, got {}",
                    self.nonce.len()
                ),
            });
        }
        if self.challenge_id.is_empty() || self.challenge_id.len() > MAX_CHALLENGE_ID_LEN {
            return Err(TomProtocolError::InvalidEnvelope {
                reason: "presence challenge_id length out of bounds".into(),
            });
        }
        let skew = now.abs_diff(self.timestamp);
        if skew > RESPONDER_ACCEPT_WINDOW_MS {
            return Err(TomProtocolError::InvalidEnvelope {
                reason: "presence challenge outside acceptance window".into(),
            });
        }
        Ok(())
    }
}

/// How the relay-activity proof inside an attestation was produced.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RelayProofType {
    /// B self-reports its activity (L1-001). Advisory only.
    SelfObserved,
    /// A third-party observer signs that B relayed (L1-003, not yet used).
    ObserverSigned,
}

/// Self-reported activity snapshot attached to an attestation.
///
/// ⚠️ EVERY field here is attacker-controlled (B fills it). It exists for
/// observability and for the L1-003 `ObserverSigned` upgrade path. The
/// anti-Sybil gate NEVER reads this struct — it reads the challenger's local
/// `RoleManager::score()` for the attester.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RelayProof {
    pub proof_type: RelayProofType,
    /// Observer identity (== attester for `SelfObserved`).
    pub observer_id: NodeId,
    /// When the observed relay happened (Unix ms, observer's clock).
    pub observed_at: u64,
    /// Bytes relayed as claimed by the observer.
    pub bytes_relayed: u64,
    /// Observer signature (empty for `SelfObserved`).
    #[serde(with = "serde_bytes")]
    pub observer_signature: Vec<u8>,
    /// Contribution score as claimed by the observer. ADVISORY ONLY.
    pub reliability_score: Option<f64>,
}

/// Payload of a `MessageType::PresenceAttestation` envelope (B → A, signed).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PresenceAttestationPayload {
    /// The challenge this attestation answers.
    pub challenge_id: String,
    /// Echo of the challenge nonce — compared byte-for-byte by A.
    #[serde(with = "serde_bytes")]
    pub nonce: Vec<u8>,
    /// B's clock at emission (Unix ms). Advisory — A never gates on it.
    pub timestamp: u64,
    /// Identity of the attester — must equal the envelope `from` AND the
    /// target A challenged.
    pub attester_id: NodeId,
    /// Identity of the challenger — must equal A's local id.
    pub challenger_id: NodeId,
    /// Self-reported activity snapshot (advisory, see [`RelayProof`]).
    pub relay_proof: RelayProof,
}

impl PresenceAttestationPayload {
    pub fn to_bytes(&self) -> Vec<u8> {
        rmp_serde::to_vec(self).expect("PresenceAttestationPayload serialization cannot fail")
    }

    pub fn from_bytes(data: &[u8]) -> Result<Self, TomProtocolError> {
        rmp_serde::from_slice(data).map_err(Into::into)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn node_id(seed: u8) -> NodeId {
        use rand::SeedableRng;
        let mut rng = rand::rngs::StdRng::seed_from_u64(seed as u64);
        let secret = tom_connect::SecretKey::generate(&mut rng);
        secret.public().to_string().parse().unwrap()
    }

    #[test]
    fn challenge_roundtrip() {
        let p = PresenceChallengePayload {
            challenge_id: "c-1".into(),
            nonce: vec![7u8; NONCE_LEN],
            timestamp: 1_000,
            challenger_id: node_id(1),
        };
        let back = PresenceChallengePayload::from_bytes(&p.to_bytes()).unwrap();
        assert_eq!(back.challenge_id, "c-1");
        assert_eq!(back.nonce, vec![7u8; NONCE_LEN]);
        assert_eq!(back.challenger_id, p.challenger_id);
    }

    #[test]
    fn challenge_validate_rejects_bad_nonce_len() {
        let p = PresenceChallengePayload {
            challenge_id: "c-1".into(),
            nonce: vec![7u8; 8],
            timestamp: 1_000,
            challenger_id: node_id(1),
        };
        assert!(p.validate(1_000).is_err());
    }

    #[test]
    fn challenge_validate_loose_window() {
        let p = PresenceChallengePayload {
            challenge_id: "c-1".into(),
            nonce: vec![7u8; NONCE_LEN],
            timestamp: 1_000_000,
            challenger_id: node_id(1),
        };
        // Inside the loose window (clock skew tolerated)
        assert!(p.validate(1_000_000 + RESPONDER_ACCEPT_WINDOW_MS - 1).is_ok());
        // Outside
        assert!(p.validate(1_000_000 + RESPONDER_ACCEPT_WINDOW_MS + 1).is_err());
    }

    #[test]
    fn attestation_roundtrip() {
        let a = PresenceAttestationPayload {
            challenge_id: "c-2".into(),
            nonce: vec![9u8; NONCE_LEN],
            timestamp: 2_000,
            attester_id: node_id(2),
            challenger_id: node_id(1),
            relay_proof: RelayProof {
                proof_type: RelayProofType::SelfObserved,
                observer_id: node_id(2),
                observed_at: 2_000,
                bytes_relayed: 42,
                observer_signature: vec![],
                reliability_score: Some(3.5),
            },
        };
        let back = PresenceAttestationPayload::from_bytes(&a.to_bytes()).unwrap();
        assert_eq!(back.challenge_id, "c-2");
        assert_eq!(back.relay_proof.proof_type, RelayProofType::SelfObserved);
        assert_eq!(back.relay_proof.bytes_relayed, 42);
    }
}
